### ISSUE TITLE
Missing asm.js annotations

### ISSUE THREAD

**Issue by romgrk** [cgiosy/xxh32#1]
I've been benchmarking hashing algos and I noticed that your implementation is missing a few asm.js annotations to appease the JS engines, details here: https://github.com/cristianbote/goober/pull/588#issuecomment-2309600140

**Comment by cgiosy** [comment]
Hello. Sorry for the delayed response!
I've looked at your [benchmark code](https://github.com/romgrk/js-benchmark/blob/master/benchmarks/hashing.js#L286), and haven't found any significant differences without that it uses an Int32Array of a pre-allocated buffer. (Additionally, DataView is faster than Int32Array in my experiments.)
This change seems difficult to apply to this library, which takes a buffer as input directly. It seems like a good idea to add a function that takes text as input.
Could you explain in more detail what other parts need to be changed?

**Comment by cgiosy** [comment]
Here are the results for [the modified benchmark](https://github.com/cgiosy/js-benchmark/blob/master/benchmarks/hashing.js) (on my M1 Macbook Air):
```
### node: v22.6.0 ###
CASE: murmur2_unmodified: ##################................................   37.57% (426 ops) (2.347 ms/op)
CASE: murmur2:            ############################......................   56.53% (641 ops) (1.562 ms/op)
CASE: murmur2_dataview:   ############################......................   57.94% (657 ops) (1.524 ms/op)
CASE: xxh:                ##########################################........   84.04% (953 ops) (1.049 ms/op)
CASE: xxh_dataview:       ##################################################  100.00% (1,134 ops) (0.8818 ms/op)
CASE: fnv-1a:             ###################...............................   38.80% (440 ops) (2.275 ms/op)
CASE: djb2a:              #######################...........................   46.74% (530 ops) (1.887 ms/op)
CASE: goober:             #####################.............................   42.42% (481 ops) (2.081 ms/op)
```

**Comment by romgrk** [comment]
Good to know, I'll close the issue then. The few modifications that exist in the benchmark repo might explain why the annotations make a difference there (the V8 disassembly was clear that they were needed though).

Thanks for sharing about the `DataView`, I'm in the process of implementing a light replacement for EmotionCSS at MUI, and I'll probably be picking your implementation of xxh for the hashing (unless I can find a way to avoid, hashing in JS is painful).
